### ISSUE TITLE
Syntax error with space in pool name. 

### ISSUE THREAD

**Issue by 12nick12** [bahamas10/zfs-prune-snapshots#1]
./zfs-prune-snapshots: line 145: Shows@data_1534448870  1534448871: syntax error: invalid arithmetic operator (error token is "@data_1534448870 1534448871")

I know it's old and I shouldn't have a space, but any chance you could help fix it? I looked thru the code, but I'm not super good with bash.

**Comment by bahamas10** [comment]
ah! interesting.  and that's totally fine - if it's a valid ZFS name then it *should* work with this script (ie. this script *should* support it)... i'll have a patch for you in a second.

**Comment by 12nick12** [comment]
Thanks a million

**Comment by bahamas10** [comment]
Tested and working!

create datasets with space in the name

```
# zfs create goliath/foo
# zfs create 'goliath/foo/name with spaces' 
# zfs snapshot 'goliath/foo/name with spaces@test'
```

Prune it successfully

```
# ./zfs-prune-snapshots -n 1s goliath/foo
removing goliath/foo/name with spaces@test: 18 seconds old <dry-run: no action taken>
# ./zfs-prune-snapshots 1s goliath/foo
removing goliath/foo/name with spaces@test: 26 seconds old
# ./zfs-prune-snapshots 1s goliath/foo
#
```

If the latest commit doesn't fix it feel free to reopen the issue, thanks :)

**Comment by 12nick12** [comment]
Thanks for the quick response. I'll let you know.

**Comment by 12nick12** [comment]
works perfect.
