### ISSUE TITLE
Feature request - dry-run

### ISSUE THREAD

**Issue by yuriw** [bahamas10/zfs-prune-snapshots#12]
It'd be great if we had an option to run `dry-run` or something else that would show an amount of space taken by zfs snapshots.

**Comment by yuriw** [comment]
oops see `-n` so withdrawn party, still if API allows, would be great to show sizes

**Comment by bahamas10** [comment]
i think this would be really cool to see as well.  I'll look into it.

**Comment by bahamas10** [comment]
see: https://github.com/bahamas10/zfs-prune-snapshots/issues/15#issuecomment-982214080
