### ISSUE TITLE
Dealing with snapshots that have dependent clones

### ISSUE THREAD

**Issue by RaananHadar** [bahamas10/zfs-prune-snapshots#16]
Hi,
Love the project, extremely useful.

When cleaning up, I am getting alot of ```snapshot has dependent clones use '-R' to destroy the following datasets:```

Would be really helpful if there was a safe was to deal with this in batch.

**Comment by bahamas10** [comment]
`-R` added in `v1.3.0` to allow for recursive deletes - that should fix this issue!

https://github.com/bahamas10/zfs-prune-snapshots/commit/482420faba96352c07a8292c5bd61c048397df2e
