### ISSUE TITLE
Enhancement - check permissions during dry run

### ISSUE THREAD

**Issue by MAP-admin-one** [bahamas10/zfs-prune-snapshots#23]
A nifty improvement might be if the dry run option also confirmed whether you had the permissions to actually do the deletion.

e.g. you can do a dry run without sufficient rights and it's a bit misleading.

I do note that the 'native' zfs destroy has the same issue, so perhaps this is either everyone's preferred behaviour, or it's difficult to implement.

**Comment by bahamas10** [comment]
I get where you're coming from but I disagree that this should be a feature - the only way to check permissions FOR SURE is to actually attempt the operation and catch an error.  this is exactly how `zfs destroy` works and most other tools so i'm fine with that precedent.
