### ISSUE TITLE
time for a release?

### ISSUE THREAD

**Issue by HRio** [bahamas10/zfs-prune-snapshots#3]
What do you think, is it time for a first release of this? 

I would like to include this script in Alpine Linux and it would help if its tagged.

**Comment by bahamas10** [comment]
Yes! Sorry for the late response, I was out of town for the last 2 weeks or so... I'm going to get right on that now for this and `zfs-snapshot-all`

**Comment by bahamas10** [comment]
`v1.0.0` is released!

I have added (included in the release):

1. `-V` to print the version number
2. A `LICENSE` file since most distros will probably want that
3. A `CHANGES.md` file as a changelog for future versions
4. A manpage

Thank you for your interest in this project :)

**Comment by HRio** [comment]
@bahamas10 big thanks! 

Regarding the man page I see you use md2man-roff. Have you seen this tool  https://git.sr.ht/~sircmpwn/scdoc?

https://repology.org/metapackage/scdoc/versions

**Comment by bahamas10** [comment]
@HRio :o I will check it out! honestly, I hate having to rely on `ruby` for this and would prefer something simpler, thanks!

**Comment by HRio** [comment]
@bahamas10 now in alpine linux https://git.alpinelinux.org/cgit/aports/commit/?id=f4a67e14
